# Generated by Django 5.2.11 on 2026-02-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_add_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='total_budget',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
